### PR TITLE
Change UNLICENSE file to use HTTPS link

### PR DESCRIPTION
**Pull request by Rotzbua**

### CODE REVIEW

**Comment by bendiken** [comment]
Thanks, but this will need some thought on my part, as it would entail the first change of the `UNLICENSE` file in a decade.

**Comment by Hexstream** [comment]
Feel free to think about this, but as far as I'm concerned, the Unlicense text has *already* changed, in a way.

That's because the Unlicense site has always said (or since times immemorial, at least) `You should feel free, though, to leave out the last line containing the link to this site, if that's your preference.`

I initially chose to exercise this option to leave out the last line. At that time I thought it was a bit too "spammy" or something. Perhaps I did not realize at that point that I would use this license for ALL of my projects going forward (except the CLHS wrapper which wraps a proprietary component.) I have long been planning to go back and update all my Unlicense instances to add the last line back in, but that hasn't happened yet (because I haven't really done any library development in the past 5 years, I was doing website stuff).

So, we finally get to the point: Recently, the license detection library that GitHub uses [got just a little stricter](https://github.com/benbalter/licensee/issues/229) in its confidence intervals, and as a result GitHub no longer recognizes the Unlicense if the last line is left out. So, pragmatically, the last line is no longer optional and so anyone who had left out should put it back in (if they want to take advantage of GitHub license detection in particular). I guess I would count that as effectively a "change" in the license text.

Anyway, everything is definitely and inevitably going `https` so personally I would make this change sooner than later.

**Comment by mlinksva** [comment]
Changing the text to https won't hurt detection [by licensee](https://github.com/benbalter/licensee/pull/293), motivated by other licenses whose canonical versions have made that change. I'm kind of annoyed by any changes at all to license texts, but this one is kind of understandable.

If the last line is really intended to be optional and the text is often deployed without that line, I suggest getting it wrapped in `<optional>` tags at https://github.com/spdx/license-list-XML/blob/master/src/Unlicense.xml ... licensee doesn't currently utilize that data source, but it might in the fullness of time.

**Comment by bendiken** [comment]
Thanks for the input guys. I agree that this needs to be done, painful as it is. Merging.

**Comment by Hexstream** [comment]
[**_GitHub now properly recognizes The Unlicense both with and without the optional line!_**](https://github.com/unlicense/unlicense.org/pull/61#issuecomment-2468903107) 🎉

**Pull request merged**
